import { useCallback, useEffect, useState } from "react";
import { API_BASE } from "@/app/lib/api";
import { formatShanghaiDateTime } from "@/app/lib/date";
import type { RequestLog } from "@/app/features/shared/types";

type RequestLogsPageProps = { connected: boolean; onToast: (message: string) => void };

export function RequestLogsPage({ connected, onToast }: RequestLogsPageProps) {
  const [items, setItems] = useState<RequestLog[]>([]); const [total, setTotal] = useState(0); const [requestType, setRequestType] = useState("");
  const [startTime, setStartTime] = useState(""); const [endTime, setEndTime] = useState(""); const [expanded, setExpanded] = useState<number | null>(null); const [loading, setLoading] = useState(false);
  const load = useCallback(async () => { if (!connected) { setItems([]); setTotal(0); return; } setLoading(true); try { const params = new URLSearchParams({ page_size: "100" }); if (requestType) params.set("request_type", requestType); if (startTime) params.set("start_time", String(Math.floor(new Date(startTime).getTime() / 1000))); if (endTime) params.set("end_time", String(Math.floor(new Date(endTime).getTime() / 1000))); const response = await fetch(`${API_BASE}/api/request-logs?${params}`); if (!response.ok) throw new Error(); const data = await response.json(); setItems(data.items); setTotal(data.total); } finally { setLoading(false); } }, [connected, requestType, startTime, endTime]);
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, [load]);
  const clear = async () => { if (!window.confirm("确定清空全部请求日志吗？")) return; const response = await fetch(`${API_BASE}/api/request-logs`, { method: "DELETE" }); if (!response.ok) return; setItems([]); setTotal(0); setExpanded(null); onToast("请求日志已清空"); };
  return <section className="content config-content request-logs-page"><div className="page-section-head"><div><p className="eyebrow">REQUEST HISTORY</p><h1>请求日志</h1><p>查看文稿、封面、配音、视频搜索词和无版权素材服务的本地请求记录。</p></div><button className="danger-outline" disabled={!connected || !total} onClick={clear}>清空日志</button></div><div className="log-filters"><label>请求类型<select value={requestType} onChange={event => setRequestType(event.target.value)}><option value="">全部类型</option><option value="文稿生成">文稿生成</option><option value="标签话题生成">标签话题生成</option><option value="封面生成">封面生成</option><option value="配音生成">配音生成</option><option value="视频搜索词生成">视频搜索词生成</option><option value="无版权视频搜索">无版权视频搜索</option></select></label><label>开始时间<input type="datetime-local" value={startTime} onChange={event => setStartTime(event.target.value)} /></label><label>结束时间<input type="datetime-local" value={endTime} onChange={event => setEndTime(event.target.value)} /></label><button className="secondary" onClick={() => { setRequestType(""); setStartTime(""); setEndTime(""); }}>重置筛选</button></div><div className="log-list-head"><b>请求记录</b><span>{loading ? "加载中…" : `共 ${total} 条`}</span></div><div className="request-log-list">{items.map(item => <article key={item.id} className={expanded === item.id ? "expanded" : ""}><button className="log-summary" onClick={() => setExpanded(expanded === item.id ? null : item.id)}><span className={`log-type ${item.request_type}`}>{item.request_type}</span><code>{item.request_url}</code><time>{formatShanghaiDateTime(item.created_at)}</time><i>{expanded === item.id ? "收起" : "参数"}</i></button>{expanded === item.id && <div className="log-params"><b>请求参数</b><pre>{JSON.stringify(item.request_params, null, 2)}</pre></div>}</article>)}{!items.length && !loading && <div className="panel-empty">暂无符合条件的请求日志</div>}</div></section>;
}
